apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stoic-api
  name: stoic-api
  namespace: testing
spec:
  replicas: 4
  selector:
    matchLabels:
      app: stoic-api
  strategy: 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: stoic-api
    spec:
      containers:
      - image: docker.io/thangeshbabu/stoic-api:1.0.0
        imagePullPolicy: Always
        name: stoic-api-container
        ports:
        - containerPort: 8080
        resources: 
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always
