apiVersion: v1
kind: Service
metadata:
  labels:
    app: stoic-api
  name: test
  namespace: testing
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: stoic-api
  type: ClusterIP
